name: FortunePunishments
author: deathibring
description: OresOfFortune's Infraction System.
version: 1.0-SNAPSHOT
api-version: 1.19
load: POSTWORLD
main: dev.oof.punish.PunishmentsCore
commands:
  kick:
  ban:
  mute:
  phistory:
  premove: